name: Test Windows

on:
  push:
    paths:
      - "**/*.go"
      - "**/*.c"
      - "**/*.h"
      - ".github/workflows/test_windows.yaml"
  workflow_dispatch:

jobs:
  run_test:
    strategy:
      fail-fast: true
      matrix:
        go_version:
          - 1.15.0
        targets:
          - windows/amd64

    runs-on: windows-latest
    steps:
    - name: Set up scoop
      run: |
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh');
        echo "::add-path::$HOME\scoop\shims";

    - name: Debug PATH
      run: echo "$Env:Path"

    - name: Set up scoop extras
      run: scoop bucket add extras;

    - name: Install packages
      run: scoop install wget unzip

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
        stable: true

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Godot 3.2.2 server
      run: |
        wget https://downloads.tuxfamily.org/godotengine/3.2.2/Godot_v3.2.2-stable_win64.exe.zip
        unzip Godot_v3.2.2-stable_win64.exe.zip -d ./
      shell: bash

    - name: Get dependencies
      run: go get -v -t -d ./...
      shell: bash

    # - name: Go get goimports
    #   run: go get golang.org/x/tools/cmd/goimports
    #   shell: bash

    # - name: Go generate
    #   run: go generate
    #   shell: bash

    - name: Build test
      run: | # need to run this twice to get a useful error message on failure
        go run mage.go -v buildtest || go run mage.go -v buildtest
      shell: bash
      env:
        GODOT_BIN: ./Godot_v3.2.2-stable_win64.exe

    - name: List Artifacts Directory
      run: ls -alh test/project/libs
      shell: bash

    - name: List CWD
      run: ls -alh .
      shell: bash

    - name: Run Test
      run: ./Godot_v3.2.2-stable_win64.exe --verbose -v -d --path test/project/
      shell: bash
      env:
        cgocheck: 2
        LOG_LEVEL: "trace"
        TEST_USE_GINKGO_WRITER: 1
        LANG: "en_US.utf8"
        CI: 1
